name: Package on Push to Main

on:
  push:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 压缩项目文件夹为 zip 包
    - name: Compress project into zip
      run: |
        zip -r project.zip . -x "*.git*" "*.github*" # 可根据需求排除不必要的文件

    # 将压缩包作为构建产物上传
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: project-zip
        path: project.zip
