name: Package Project

on:
  push:
    branches:
      - main

jobs:
  front-end:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Set up nodejs
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: '18'

    # - name: Package Vue
    #   run: |
    #     cd front-end/YIT
    #     npm install
    #     npm run build

    # - name: Copy front-end build to back-end
    #   run: |
    #     cp -r front-end/YIT/dist/ back-end/yit/yit/src/main/resources/static/

    # - name: Set up Java
    #   uses: actions/setup-java@v4
    #   with:
    #     distribution: 'temurin'
    #     java-version: '21'

    # - name: Build back-end
    #   run: |
    #     cd back-end/yit/yit
    #     chmod +x ./mvnw
    #     ./mvnw clean install -DskipTests
      
    # - name: Upload JAR Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: yit-jar
    #     path: back-end/yit/yit/target/*.jar

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # 设置 Buildx

    - name: Build Docker image
      run: |
        cd back-end/python-server
        docker build -t yit-python-server:$GITHUB_SHA .  

    - name: Save Docker image as tar file
      run: |
        docker save -o yit-python-server-$GITHUB_SHA.tar yit-python-server:$GITHUB_SHA
        echo ${{ secrets.REMOTE_SSH_KEY }} > ssh_key
        scp -i ssh_key yit-python-server-$GITHUB_SHA.tar root@${{ secrets.REMOTE_HOST }}:/root/yit/
  
    # - name: Copy Docker image to remote server
    #   uses: appleboy/ssh-action@v1.2.0
    #   with:
    #     host: ${{ secrets.REMOTE_HOST }}
    #     username: ${{ secrets.REMOTE_USER }}
    #     key: ${{ secrets.REMOTE_SSH_KEY }}
    #     port: ${{ secrets.REMOTE_PORT }}
    #     script: |
          
