name: Package Project

on:
  push:
    branches:
      - main

jobs:
  front-end:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Set up nodejs
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: '18'

    # - name: Package Vue
    #   run: |
    #     cd front-end/YIT
    #     npm install
    #     npm run build

    # - name: Copy front-end build to back-end
    #   run: |
    #     cp -r front-end/YIT/dist/ back-end/yit/yit/src/main/resources/static/

    # - name: Set up Java
    #   uses: actions/setup-java@v4
    #   with:
    #     distribution: 'temurin'
    #     java-version: '21'

    # - name: Build back-end
    #   run: |
    #     cd back-end/yit/yit
    #     chmod +x ./mvnw
    #     ./mvnw clean install -DskipTests
      
    # - name: Upload JAR Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: yit-jar
    #     path: back-end/yit/yit/target/*.jar

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  # 设置 Buildx

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 用户名
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 密码或访问令牌

    - name: Build Docker image
      run: |
        cd back-end/python-server
        pwd
        ls
        docker build -t python-server:$GITHUB_SHA .  # 用当前的 Git commit hash 标记 Docker 镜像

    - name: Push Docker image
      run: |
        docker push ykn0309/python-server:$GITHUB_SHA  # 将镜像推送到 Docker Hub
