name: Package Vue

on:
  push:
    branches:
      - main

jobs:
  front-end:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up nodejs
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Package Vue
      run: |
        cd front-end/YIT
        npm install
        npm run build
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Build back-end
      run: |
        cd back-end/yit/yit
        chmod +x ./mvnw
        ./mvnw clean install -DskipTests
